In [3]:
import pandas as pd
import numpy as np
import datetime
import time
from calendar import monthrange
from pprint import pprint

In [43]:
df = pd.read_csv("../../../Data/vw_Incident.csv",encoding='latin-1',low_memory=False)

In [44]:
from sklearn.utils import resample
df = resample(df, n_samples=100, random_state=1234)

In [55]:
dfcopy = df.copy()
cols = ["TimeTaken", "rolling_mean", "rolling_median", "rolling_std", "Created_On", "ResolvedDate"]
for col in df:
    if col not in cols:
        del dfcopy[col]
        
dfcopy["Created_On"] = pd.to_datetime(df["Created_On"])
dfcopy["ResolvedDate"] = pd.to_datetime(df["ResolvedDate"])
dfcopy["TimeTaken"] = (dfcopy["ResolvedDate"] - dfcopy["Created_On"]).astype('timedelta64[s]')

dfcopy.sort_values(by="Created_On", inplace=True)

dfcopy["rolling_mean"] = dfcopy["TimeTaken"].rolling(window=10).mean()
dfcopy["rolling_median"] = dfcopy["TimeTaken"].rolling(window=10).median()
# dfcopy["rolling_max"] = dfcopy["TimeTaken"].rolling(window=10).max()
# dfcopy["rolling_min"] = dfcopy["TimeTaken"].rolling(window=10).min()
dfcopy["rolling_std"] = dfcopy["TimeTaken"].rolling(window=10).std()
dfcopy["rolling_sum"] = dfcopy["TimeTaken"].rolling(window=10).sum()


dfcopy.dropna(subset=["rolling_mean"], inplace=True)
dfcopy[cols]

,TimeTaken,rolling_mean,rolling_median,rolling_std,Created_On,ResolvedDate
30385,314.0,623080.6,275616.5,988960.891862,2017-03-02 07:06:40,2017-03-02 07:11:54
33950,795155.0,702531.8,290982.0,965024.404535,2017-03-06 00:55:59,2017-03-15 05:48:34
32399,84527.0,681878.4,275616.5,976945.636858,2017-03-07 10:33:45,2017-03-08 10:02:32
34086,266460.0,604658.4,263395.0,976129.263374,2017-03-07 12:47:25,2017-03-10 14:48:25
32427,990561.0,378251.0,263395.0,363531.563314,2017-03-07 17:18:58,2017-03-19 04:28:19
32428,421.0,353416.6,263395.0,381403.575728,2017-03-07 17:19:48,2017-03-07 17:26:49
35921,970740.0,421400.3,263395.0,426898.450525,2017-03-07 22:15:48,2017-03-19 03:54:48
10,1065432.0,527905.9,530807.5,442751.689205,2017-03-12 21:16:04,2017-03-25 05:13:16
22267,884063.0,531800.3,530807.5,446011.159577,2017-03-18 00:37:56,2017-03-28 06:12:19
7644,333067.0,539074.0,564111.0,441663.940096,2017-03-21 15:24:12,2017-03-25 11:55:19
15097,900375.0,629080.1,839609.0,410266.636668,2017-03-21 17:53:06,2017-04-01 03:59:21
15123,187150.0,568279.6,608565.0,427606.094871,2017-03-22 09:03:44,2017-03-24 13:02:54
7794,406797.0,600506.6,645430.0,398231.787355,2017-03-23 09:50:36,2017-03-28 02:50:33
7962,549534.0,628814.0,716798.5,381560.391925,2017-03-24 17:16:06,2017-03-31 01:55:00
753,24753.0,532233.2,478165.5,401531.136831,2017-03-24 20:28:13,2017-03-25 03:20:46
8060,189898.0,551180.9,478165.5,377392.266354,2017-03-26 13:17:36,2017-03-28 18:02:34
8165,499.0,454156.8,369932.0,382231.497790,2017-03-27 17:02:30,2017-03-27 17:10:49
8222,72506.0,354864.2,261482.5,331380.617012,2017-03-28 06:58:26,2017-03-29 03:06:52
986,171171.0,283575.0,188524.0,277125.792019,2017-03-28 08:22:20,2017-03-30 07:55:11
8342,757554.0,326023.7,188524.0,315414.375506,2017-03-28 22:49:50,2017-04-06 17:15:44
23147,1884613.0,424447.5,188524.0,567433.285425,2017-03-29 14:14:53,2017-04-20 09:45:06
23289,1731051.0,578837.6,298347.5,692047.234548,2017-03-30 14:04:55,2017-04-19 14:55:46
8682,176906.0,555848.5,183402.0,702141.994934,2017-03-31 13:12:46,2017-04-02 14:21:12
23452,411028.0,541997.9,183402.0,703644.886964,2017-03-31 13:37:06,2017-04-05 07:47:34
23553,10629.0,540585.5,183402.0,704811.701814,2017-04-01 20:27:02,2017-04-01 23:24:11
8953,506788.0,572274.5,293967.0,694338.569053,2017-04-04 14:34:43,2017-04-10 11:21:11
23691,3024.0,572527.0,293967.0,694107.957346,2017-04-05 07:30:18,2017-04-05 08:20:42
23706,1367548.0,702031.2,458908.0,711055.297106,2017-04-05 13:47:37,2017-04-21 09:40:05
1731,2328396.0,917753.7,632171.0,846449.096753,2017-04-05 17:45:20,2017-05-02 16:31:56
16387,92313.0,851229.6,458908.0,885671.026653,2017-04-06 14:25:19,2017-04-07 16:03:52
...,...,...,...,...,...,...
12184,18265.0,400054.8,205384.0,485333.953423,2017-05-25 12:42:45,2017-05-25 17:47:10
12198,126752.0,257505.7,151753.5,271599.322997,2017-05-25 15:11:37,2017-05-27 02:24:09
26964,511448.0,290975.0,180382.5,281002.136414,2017-05-26 15:43:24,2017-06-01 13:47:32
5138,1565342.0,424107.9,319100.0,489237.808188,2017-05-30 16:27:26,2017-06-17 19:16:28
27439,24675.0,422700.7,319100.0,490488.023739,2017-05-31 20:23:31,2017-06-01 03:14:46
27532,24124.0,369706.8,112522.5,503182.130758,2017-06-01 12:39:28,2017-06-01 19:21:32
20469,417569.0,333678.2,112522.5,483213.266383,2017-06-06 23:00:18,2017-06-11 18:59:47
27973,1248649.0,458409.3,272160.5,544936.146159,2017-06-07 19:37:54,2017-06-22 06:28:43
27984,336919.0,437203.6,231835.5,545146.196420,2017-06-07 21:43:06,2017-06-11 19:18:25
13338,1019562.0,529330.5,377244.0,559172.665985,2017-06-08 08:41:00,2017-06-20 03:53:42
13547,336.0,527537.6,377244.0,561019.085068,2017-06-09 20:02:42,2017-06-09 20:08:18
20949,3753.0,515237.7,377244.0,572022.732544,2017-06-12 13:51:05,2017-06-12 14:53:38
28319,14532.0,465546.1,180797.0,593566.372214,2017-06-12 16:51:27,2017-06-12 20:53:39
13686,628577.0,371869.6,180797.0,459488.185096,2017-06-13 00:07:17,2017-06-20 06:43:34
13777,10896.0,370491.7,180521.5,460664.181581,2017-06-13 15:34:48,2017-06-13 18:36:24
28453,794685.0,447547.8,377244.0,460735.684702,2017-06-13 19:39:39,2017-06-23 00:24:24
28530,88524.0,414643.3,212721.5,474654.100926,2017-06-14 14:07:19,2017-06-15 14:42:43
21225,10840.0,290862.4,51528.0,386140.896154,2017-06-14 17:37:24,2017-06-14 20:38:04
6603,98285.0,266999.0,51528.0,390329.398092,2017-06-15 21:19:56,2017-06-17 00:38:01
28713,11825.0,166225.3,13178.5,292199.069571,2017-06-16 10:34:20,2017-06-16 13:51:25
14192,243174.0,190509.1,51528.0,286923.814797,2017-06-17 03:03:33,2017-06-19 22:36:27
21508,29196.0,193053.4,58860.0,285191.323734,2017-06-19 14:42:18,2017-06-19 22:48:54
14330,5051.0,192105.3,58860.0,285865.711171,2017-06-20 03:49:47,2017-06-20 05:13:58
21580,2445.0,129492.1,20510.5,245341.530606,2017-06-20 06:11:21,2017-06-20 06:52:06
28869,171651.0,145567.6,58860.0,241950.481773,2017-06-20 07:23:36,2017-06-22 07:04:27
21590,74899.0,73589.0,52047.5,80754.624316,2017-06-20 08:23:55,2017-06-21 05:12:14
6950,91291.0,73865.7,52047.5,80816.200993,2017-06-21 06:09:30,2017-06-22 07:31:01
14455,9076.0,73689.3,52047.5,80970.831704,2017-06-21 09:20:06,2017-06-21 11:51:22
29026,351.0,63895.9,20510.5,83547.013535,2017-06-21 16:46:18,2017-06-21 16:52:09
14629,19542.0,64667.6,24369.0,83046.751120,2017-06-23 06:14:33,2017-06-23 11:40:15

number of cases created within 4 hours should be a good one though!